properNouns = [
    "Donald Trump",
    "Joe Biden",
    "Ninja",
    "Proton Bomb",
    "He Who Shall Not Be Named",
    "Fake unknown",
    "Donald Duck",
    "Probably Sharts",
    "Barack Obama",
    "Elon Musk",
    "Grumpy Cat",
    "David Beckham",
    "Albert Einstein",
    "Leonardo DiCaprio",
    "Taylor Swift",
    "Kanye West",
    "Oprah Winfrey",
    "Steve Jobs",
    "Bill Gates",
    "Malala Yousafzai",
    "Nelson Mandela",
    "Mahatma Gandhi",
    "Thomas Edison",
    "Ada Lovelace",
    "Alexander Graham Bell",
    "Charles Darwin",
    "Marie Curie",
    "Isaac Newton",
    "Galileo Galilei",
    "Albert Camus",
    "Frida Kahlo",
    "Vincent Van Gogh",
    "Pablo Picasso",
    "Leonardo da Vinci",
    "Michelangelo",
    "Johannes Vermeer",
    "Claude Monet",
    "Pierre-Auguste Reno",
    "William Shakespeare",
    "George Orwell",
    "J.R.R. Tolkien",
    "Jane Austen",
    "Charles Dickens",
    "Fyodor Dostoevsky",
    "Emily Brontë",
    "Charlotte Brontë",
    "Virginia Woolf",
    "Harper Lee",
    "J.K. Rowling",
    "Mark Twain",
    "Edgar Allan Poe",
    "Agatha Christie",
    "Ernest Hemingway",
    "George Orwell",
    "Harper Lee",
    "J.R.R. Tolkien",
    "J.K. Rowling",
    "Jane Austen",
    "Leo Tolstoy",
    "Mark Twain",
    "Stephen King",
    "Toni Morrison",
    "William Shakespeare",
    "He Who Must Be Obeyed",
    "The Great Sock Eater",
    "Lord McSassypants",
    "Baron Von Snoodle",
    "The Incredible Sulk",
    "Zorgon Destroyer",
    "Balthazar McSnazz",
    "The Mysterious Donut",
    "The Duke of Disco",
    "The Earl of Eccentric",
    "The Viscount Vexation",
    "The Marquis Mischief",
    "The King Kookiness",
]
